services:
  bio-links:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bio-links
    restart: unless-stopped
    ports:
      - '${PORT}:80'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
